[tool.poetry]
name = "mesa"
version = "0.1.0"
description = ""
authors = ["Tlaven <2515406347@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
